# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, null=True, verbose_name='\u6559\u5b66\u7279\u70b9'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='\u516c\u5f0f\u804c\u4f4d'),
        ),
    ]
